---
title: "Course Materials"
date: today
---

This page contains course materials used during the demonstration and practical exercises.

# Week 1

- [Tidy data conceptual walkthrough](materials/w01_tidy_management/tidy_data_conceptual.html) ([QMD](materials/downloads/w01_tidy_management/tidy_data_conceptual.qmd))

# Week 2

- [Data wrangling in dplyr](materials/w02_wrangling/dplyr_walkthrough.html) ([QMD](materials/downloads/w02_wrangling/dplyr_walkthrough.qmd))
- [Joins tutorial](materials/w02_wrangling/joins_tutorial.html) ([QMD](materials/downloads/w02_wrangling/joins_tutorial.qmd))
- [Strings in R with stringr](materials/w02_wrangling/strings_stringr.html) ([QMD](materials/downloads/w02_wrangling/strings_stringr.qmd))

# Week 3

- [Compact data validation with validate (Psychology Survey Example)](materials/w03_automation/validate_bfi.html) ([QMD](materials/downloads/w03_automation/validate_bfi.qmd))
- [ECG physio processing script](materials/w03_automation/read_physio.R) ([Data](materials/w03_automation/files/ecg_physio.zip))

# Week 4

- [Functional programming and reproducibility](materials/w04_advanced/reproducibility_good_programming.html) ([QMD](materials/downloads/w04_advanced/reproducibility_good_programming.qmd))
- [QA for Antisaccade Data Using List-Columns](materials/w04_advanced/qa_eye_data.html) ([QMD](materials/downloads/w04_advanced/qa_eye_data.qmd); [Data](materials/files/eyeDataList_14Jul2014.Rdata), [Run-level subject info](materials/files/subj_info_run_level.csv.gz), [Subject info](materials/files/subj_info.csv.gz))
