---
title: "PSYC 859 Syllabus"
---

# Course Description

This graduate course is intended to provide an applied introduction to data management and data visualization in the social sciences. In order to take full advantage of modern statistical methods (e.g., structural equation models), competency in data management, semi-automated processing, and data wrangling is prerequisite. Likewise, prior to employing inferential statistics, exploratory visualization and analysis is essential to facilitate data cleaning and to form an initial understanding of patterns in the data. This course will cover both the principles and practice of data management, visualization, and exploratory analysis for summarizing quantitative data. In addition, students will learn data science skills to manage and visualize "big data," where the size or complexity of the dataset defies traditional techniques.

Applications of data management, visualization, and analysis will use the *R* statistical programming language. *R* is quickly becoming the *lingua franca* in data science across disciplines and offers unparalleled tools for data analysis and visualization.

# Learning Objectives

- Design and implement reproducible data workflows for managing, cleaning, and documenting complex datasets using modern R-based tools.
- Use exploratory data analysis and visualization as tools for scientific reasoning, including identifying patterns, anomalies, uncertainty, and data limitations.
- Apply evidence-based principles of graphical perception and design to create clear, accurate, and interpretable quantitative graphics.
- Critically evaluate and redesign data visualizations in scientific research and public communication, justifying design choices and trade-offs.
- Communicate substantive insights through publication-quality and presentation-ready visualizations, integrating narrative, annotation, and appropriate use of modern visualization technologies.

# Prerequisites

PSY 830 (Statistical Methods in Psychology I) or graduate course equivalent.

Students are expected to have a basic understanding of *R* or another high-level programming language (e.g., Python). Minimally, students should understand basic principles of computer programming, including 1) conditional logic (if/else) and logical operators (e.g., equality); 2) basic data types (in *R*, vectors, lists, data.frames, matrices, and arrays), 3) flow control (for/while loops, next, break), 4) import and export of data from text files, and 5) subsetting data using basic *R* syntax such as x[1:10, c(1,5)].

# Required Textbooks

- Tufte, E. R. (2001). *The visual display of quantitative information* (2nd ed.). Cheshire, CT: Graphics Press.
- Wickham, H. (2025). *ggplot2: Elegant graphics for data analysis* (3rd ed.). New York: Springer. Please use the online (not-yet-published) version here: https://ggplot2-book.org.
- Wickham, H., Cetinka-Rundel, M., & Grolemund, G. (2023). *R for Data Science: Import, Tidy, Transform, Visualize, and Model Data* (2nd edition). O'Reilly Media. Available online: https://r4ds.hadley.nz.

# Recommended Textbooks

- Chang, W. (2019). *R graphics cookbook* (2nd ed.). Sebastopol, CA: O'Reilly. (Especially useful for those with little background in *R* and *ggplot2*). Available online: https://r-graphics.org.
- Cleveland, W. S. (1994). *The elements of graphing data* (2nd ed.). Summit, NJ: Hobart Press.

# Required Software

- *R* (free): http://cran.r-project.org/
- RStudio (free): http://www.rstudio.com/
- Inkscape (free): https://inkscape.org/en/
- Gimp (free): http://www.gimp.org
- *R* packages to install: tidyverse, shiny, ggplotly, broom, ggplot2, tidymodels

# Class Structure

With a few exceptions, class will be structured into three blocks as follows:

- 9:00-10:10am Figure critique, lecture, and discussion of readings
- 10:10am-10:20am Break
- 10:20am-11:30am R demonstration and practical exercise

During the R demonstration, we will work on a data-related project together, so please bring a laptop with the above software and packages loaded. Let me know if this will be a difficulty for you so that we can arrange alternative plans.

# Evaluation

Although the course will review the principles of effective data visualization (e.g., graphical perception), the course is primarily intended to facilitate your applied skills managing and visualizing data. Consequently, there will be no formal exams or quizzes. Instead, your grade will be based primarily on figure critiques, take-home exercises, participation, and three projects. Students are encouraged to bring a dataset that is relevant to their research for use in each project. If possible, a challenging dataset (one that defies simple management in a spreadsheet format) will provide better opportunities to learn advanced data management and visualization skills.

All projects are to be completed individually. Although you are encouraged to discuss data management and visualization challenges with your classmates, you'll get the most benefit from the course by developing projects yourself.

- 15% Participation, as defined by attending class, contributing to reading discussions, engagement with lab exercises, and otherwise contributing to scholarly discourse.
- 10% Figure critiques and data exercises. In the first part of the semester, students will complete take-home data exercises to become familiar with managing, tidying, and wrangling data in *R*. In the latter half of the semester, students will be expected to submit a critique of at least one figure or table. The critique can be brief, perhaps in bullet form, but should highlight key strengths and limitations of the display, as well as suggestions for alternative visualizations. One (or perhaps a few) figures will be discussed at the beginning of class before the discussion of readings.

Assignments will be due by 8am on Wednesdays to provide time to review them and incorporate into class discussion.

- 5% Data quality assurance and processing proposal. Due: 1/29 (Week 4)
- 15% Data quality assurance project (code and output). Due: 2/12 (Week 6)
- 15% Conceptual figure/infographic project. Due: 3/5 (Week 9)
- 5% Final project proposal. Due: 3/26 (Week 11)
- 10% Final presentation of data visualization project. Due: 4/23 (Week 14)
- 25% Data visualization final product. Due: 4/27

# Week 1 (1/8): Introduction to data management and tidy data {#week-1}

## Conceptual readings

- Briney, K., Coates, H., & Goben, A. (2020). [Foundational Practices of Research Data Management.](https://ares.lib.unc.edu/remoteauth/ares.dll?Action=10&Type=10&Value=109354827) **Research Ideas and Outcomes, 6**, e56508. https://doi.org/10.3897/rio.6.e56508
- Borer, E. T., Seabloom, E. W., Jones, M. B., & Schildhauer, M. (2009). [Some Simple Guidelines for Effective Data Management.](https://ares.lib.unc.edu/remoteauth/ares.dll?Action=10&Type=10&Value=109354826) **The Bulletin of the Ecological Society of America, 90,** 205-214. https://doi.org/10.1890/0012-9623-90.2.205
- (Optional) Borghi, J. A., & Gulick, A. E. V. (2021). [Data management and sharing: Practices and perceptions of psychology researchers.](https://ares.lib.unc.edu/remoteauth/ares.dll?Action=10&Type=10&Value=109354828) **PLOS ONE, 16,** e0252047. https://doi.org/10.1371/journal.pone.0252047

## Practical readings

- Wickham, H., Cetinka-Rundel, M., & Grolemund, G. (2023). *R for Data Science* (2nd ed.).
  - Ch. 2: Workflow: basics. https://r4ds.hadley.nz/workflow-basics.html
  - Ch. 4: Workflow: code style. https://r4ds.hadley.nz/workflow-style.html
  - Ch. 5: Data tidying. https://r4ds.hadley.nz/data-tidy.html
  - Ch. 6: Workflow: scripts and projects. https://r4ds.hadley.nz/workflow-scripts.html
  - Ch. 7: Data import. https://r4ds.hadley.nz/data-import.html
- (Supplementary) Tidyr pivoting vignette: https://tidyr.tidyverse.org/articles/pivot.html
- Tidyr cheatsheet: https://rstudio.github.io/cheatsheets/tidyr.pdf
- RStudio Data Import cheat sheet: https://rstudio.github.io/cheatsheets/data-import.pdf

# Week 2 (1/15): Data aggregation, manipulation, joins {#week-2}

- Wickham, H., Cetinka-Rundel, M., & Grolemund, G. (2023). *R for Data Science* (2nd ed.).
  - Ch. 3: Data transformation: https://r4ds.hadley.nz/data-transform.html
  - Ch. 12: Logical vectors: https://r4ds.hadley.nz/logicals.html
  - Ch. 13: Numbers: https://r4ds.hadley.nz/numbers.html
  - Ch. 14: Strings: https://r4ds.hadley.nz/strings.html
  - Ch. 16: Factors: https://r4ds.hadley.nz/factors.html
  - Ch. 19: Joins: https://r4ds.hadley.nz/joins.html
  - (Optional) Ch. 15: Regular expressions. https://r4ds.hadley.nz/regexps.html
  - (Optional) Ch. 17: Dates and times. https://r4ds.hadley.nz/datetimes.html
  - (Optional) Ch. 20: Import: spreadsheets. https://r4ds.hadley.nz/spreadsheets.html
